src/Entity/Album.php
<?php

namespace App\Entity;

use App\Repository\AlbumRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AlbumRepository::class)
 */
class Album
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="integer")
     */
    private $ReleaseYear;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Cover;

    /**
     * @ORM\ManyToOne(targetEntity=Artist::class, inversedBy="albums")
     */
    private $Artist;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getReleaseYear(): ?int
    {
        return $this->ReleaseYear;
    }

    public function setReleaseYear(int $ReleaseYear): self
    {
        $this->ReleaseYear = $ReleaseYear;

        return $this;
    }

    public function getCover(): ?string
    {
        return $this->Cover;
    }

    public function setCover(string $Cover): self
    {
        $this->Cover = $Cover;

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->Artist;
    }

    public function setArtist(?Artist $Artist): self
    {
        $this->Artist = $Artist;

        return $this;
    }
}

src/Controller/AlbumViewsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AlbumViewsController extends AbstractController
{
    /**
     * @Route("/album/views", name="album_views")
     */
    public function index(): Response
    {
        return $this->render('album_views/index.html.twig', [
            'controller_name' => 'AlbumViewsController',
        ]);
    }
}

templates/album_views/index.html.twig
<div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
    <img src="{{ asset('uploads/' ~ album.cover) }}​​" class="card-img-top" alt="{{ album.name }}​​" />
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{album.name}}</h5>
        <p class="card-text">{{album.releaseYear}}</p>
        <p>Artiste : {{album.artist.name}}</p>
        <a class="btn btn-light" href="{{path('artist_item', {'id' : album.artist.id})}}" role="button">Découvrir l'artiste</a>
      </div>
    </div>
  </div>
</div>