src/Entity/Album.php
<?php

namespace App\Entity;

use App\Repository\AlbumRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AlbumRepository::class)
 */
class Album
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="integer")
     */
    private $ReleaseYear;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Cover;

    /**
     * @ORM\ManyToOne(targetEntity=Artist::class, inversedBy="albums")
     */
    private $Artist;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getReleaseYear(): ?int
    {
        return $this->ReleaseYear;
    }

    public function setReleaseYear(int $ReleaseYear): self
    {
        $this->ReleaseYear = $ReleaseYear;

        return $this;
    }

    public function getCover(): ?string
    {
        return $this->Cover;
    }

    public function setCover(string $Cover): self
    {
        $this->Cover = $Cover;

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->Artist;
    }

    public function setArtist(?Artist $Artist): self
    {
        $this->Artist = $Artist;

        return $this;
    }
}

src/Entity/Artist.php
<?php

namespace App\Entity;

use App\Repository\ArtistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArtistRepository::class)
 */
class Artist
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Picture;

    /**
     * @ORM\ManyToOne(targetEntity=Style::class, inversedBy="Artists")
     */
    private $style;

    /**
     * @ORM\OneToMany(targetEntity=Album::class, mappedBy="Artist")
     */
    private $albums;

    public function __construct()
    {
        $this->albums = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->Picture;
    }

    public function setPicture(string $Picture): self
    {
        $this->Picture = $Picture;

        return $this;
    }

    public function getStyle(): ?Style
    {
        return $this->style;
    }

    public function setStyle(?Style $style): self
    {
        $this->style = $style;

        return $this;
    }

    /**
     * @return Collection|Album[]
     */
    public function getAlbums(): Collection
    {
        return $this->albums;
    }

    public function addAlbum(Album $album): self
    {
        if (!$this->albums->contains($album)) {
            $this->albums[] = $album;
            $album->setArtist($this);
        }

        return $this;
    }

    public function removeAlbum(Album $album): self
    {
        if ($this->albums->removeElement($album)) {
            // set the owning side to null (unless already changed)
            if ($album->getArtist() === $this) {
                $album->setArtist(null);
            }
        }

        return $this;
    }
}

src/Entity/Style.php
<?php

namespace App\Entity;

use App\Repository\StyleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StyleRepository::class)
 */
class Style
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\OneToMany(targetEntity=Artist::class, mappedBy="style")
     */
    private $Artists;

    public function __construct()
    {
        $this->Artists = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    /**
     * @return Collection|Artist[]
     */
    public function getArtists(): Collection
    {
        return $this->Artists;
    }

    public function addArtist(Artist $artist): self
    {
        if (!$this->Artists->contains($artist)) {
            $this->Artists[] = $artist;
            $artist->setStyle($this);
        }

        return $this;
    }

    public function removeArtist(Artist $artist): self
    {
        if ($this->Artists->removeElement($artist)) {
            // set the owning side to null (unless already changed)
            if ($artist->getStyle() === $this) {
                $artist->setStyle(null);
            }
        }

        return $this;
    }
}

src/Controller/ArtistViewsController.php
<?php

namespace App\Controller;

use App\Entity\Artist;
use App\Repository\ArtistRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ArtistViewsController extends AbstractController
{
    /**
     * @Route("/artist/views", name="artist_views")
     */
    public function index(ArtistRepository $artistRepository): Response
    {

        $artists = $artistRepository->findAll();
        return $this->render('artist_views/index.html.twig', [
            'artists' => $artists
        ]);
    }

    
  /**
   * @Route("/artist/{id}", name="artist_item")
   */
  public function product(Artist $artist , ArtistRepository $artistRepository): Response
  {

    $Astyle = $artistRepository->FindByStyle();
    return $this->render('artist_views/artist.html.twig', [
      'artist' => $artist,
      'astyle' =>$Astyle
    ]);
  }
}

templates/artist_views/artist.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductViewsController!{% endblock %}

{% block body %}
<div class="d-flex justify-content-center mt-5">
<div class="card" style="width: 18rem;">
  <img src="{{ asset('/uploads/' ~ artist.picture) }}​​" class="card-img-top" alt="{{ artist.name }}">
  <div class="card-body">
    <h2 class="text-center">{{artist.name}}</h2>
    <p>Style de l'artiste : {{artist.style.name}}<p>
    <h5>Les albums de l'artiste</h5>
     {% for album in artist.albums %}
     <ul class="list-group list-group-flush">
        <li class="list-group-item"> {{album.name}}</li>
    </ul>
    {% endfor %}
 <div class="card-body">
 <h5>Les artistes similaires<h5>
  {% for artist in artist.style.artists %}
    <a href="{{path('artist_item', {'id' : artist.id})}}" class="card-link">{{artist.name}}</a>
    {% endfor %}
  </div>
  </div>
</div>
</div>
{% endblock %}

templates/artist_views/artistItem.html.twig
<div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
    <img src="{{ asset('uploads/' ~ artist.picture) }}​​" class="card-img-top" alt="{{ artist.name }}​​">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{artist.name}}</h5>
        <p>Style : {{artist.style.name}}</p>
        <a class="btn btn-light" href="{{path('artist_item', {'id' : artist.id})}}" role="button">Découvrir l'artiste</a>
      </div>
    </div>
  </div>
</div>

templates/artist_views/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ArtistViewsController!{% endblock %}

{% block body %}

<div  class="container mt-5">
<h3>Tous nos artistes</h3>
{% for artist in artists %}
    {% include "artist_views/artistItem.html.twig" %}
{% endfor %}
</div>

{% endblock %}